# Generated by Django 4.2.5 on 2023-11-09 23:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('necesitaNesteo', models.BooleanField(default=True)),
                ('espesor', models.CharField(max_length=100)),
                ('proveedor', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Placa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('piezas', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Proceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('estatus', models.CharField(max_length=50)),
                ('maquina', models.CharField(max_length=100)),
                ('inicioProceso', models.DateTimeField()),
                ('finProceso', models.DateTimeField()),
                ('placa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ri_produccion.placa')),
            ],
        ),
        migrations.CreateModel(
            name='Pieza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consecutivo', models.CharField(max_length=100, unique=True)),
                ('ordenCompra', models.CharField(max_length=150)),
                ('piezas', models.IntegerField()),
                ('piezasTotales', models.IntegerField()),
                ('creadoPor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ri_produccion.material')),
                ('placas', models.ManyToManyField(blank=True, to='ri_produccion.placa')),
                ('procesos', models.ManyToManyField(blank=True, to='ri_produccion.proceso')),
            ],
        ),
    ]
