# Generated by Django 4.2.5 on 2023-11-16 02:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('espesor', models.CharField(max_length=100)),
                ('proveedor', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Placa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=350, null=True)),
                ('piezas', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Proceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('estatus', models.CharField(choices=[('error', 'Error'), ('rechazado', 'Rechazado'), ('pendiente', 'Pendiente'), ('operando', 'Operando'), ('realizado', 'Realizado')], default='pendiente', max_length=50)),
                ('maquina', models.CharField(max_length=100)),
                ('inicioProceso', models.DateTimeField()),
                ('finProceso', models.DateTimeField()),
                ('comentarios', models.CharField(blank=True, max_length=300, null=True)),
                ('prioridad', models.BooleanField(default=False)),
                ('placa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ri_produccion.placa')),
                ('realizadoPor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pieza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consecutivo', models.CharField(max_length=100, unique=True)),
                ('estatus', models.CharField(choices=[('rechazado', 'Rechazado'), ('pendiente', 'Pendiente'), ('aprobado', 'Aprobado')], default='pendiente', max_length=40)),
                ('motivoRechazo', models.CharField(blank=True, max_length=300, null=True)),
                ('fechaRechazado', models.DateTimeField(null=True)),
                ('ordenCompra', models.CharField(max_length=150)),
                ('piezas', models.IntegerField()),
                ('piezasTotales', models.IntegerField()),
                ('fechaCreado', models.DateTimeField(auto_now_add=True)),
                ('archivo_pdf', models.FileField(blank=True, null=True, upload_to='pdfs-produccion')),
                ('prioridad', models.BooleanField(default=False)),
                ('creadoPor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ri_produccion.material')),
                ('placas', models.ManyToManyField(blank=True, to='ri_produccion.placa')),
                ('procesos', models.ManyToManyField(blank=True, to='ri_produccion.proceso')),
            ],
        ),
        migrations.CreateModel(
            name='HistorialPieza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consecutivo', models.CharField(max_length=100, unique=True)),
                ('ordenCompra', models.CharField(max_length=150)),
                ('piezas', models.IntegerField()),
                ('piezasTotales', models.IntegerField()),
                ('archivo_pdf', models.FileField(blank=True, null=True, upload_to='pdfs-produccion')),
                ('prioridad', models.BooleanField(default=False)),
                ('fecha_finalizacion', models.DateTimeField()),
                ('creadoPor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ri_produccion.material')),
                ('placas', models.ManyToManyField(blank=True, to='ri_produccion.placa')),
                ('procesos', models.ManyToManyField(blank=True, to='ri_produccion.proceso')),
            ],
        ),
    ]
