# Generated by Django 4.2.5 on 2023-11-10 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ri_produccion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pieza',
            name='archivo_pdf',
            field=models.FileField(blank=True, null=True, upload_to='pdfs-produccion'),
        ),
    ]
