# Generated by Django 4.2.5 on 2023-11-16 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ri_produccion', '0002_notificacion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notificacion',
        ),
    ]
