# Generated by Django 4.2.5 on 2023-11-11 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ri_produccion', '0002_pieza_archivo_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proceso',
            name='estatus',
            field=models.CharField(choices=[('rechazado', 'Rechazado'), ('pendiente', 'Pendiente'), ('operando', 'Operando'), ('realizado', 'Realizado')], max_length=50),
        ),
    ]
