# Generated by Django 4.2.5 on 2023-11-11 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ri_produccion', '0003_alter_proceso_estatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='pieza',
            name='prioridad',
            field=models.IntegerField(default=0),
        ),
    ]
