# Generated by Django 4.2.5 on 2023-11-11 17:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ri_produccion', '0004_pieza_prioridad'),
    ]

    operations = [
        migrations.AddField(
            model_name='proceso',
            name='comentarios',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='proceso',
            name='realizadoPor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pieza',
            name='prioridad',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='proceso',
            name='estatus',
            field=models.CharField(choices=[('rechazado', 'Rechazado'), ('pendiente', 'Pendiente'), ('operando', 'Operando'), ('realizado', 'Realizado')], default='pendiente', max_length=50),
        ),
        migrations.CreateModel(
            name='HistorialPieza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consecutivo', models.CharField(max_length=100, unique=True)),
                ('ordenCompra', models.CharField(max_length=150)),
                ('piezas', models.IntegerField()),
                ('piezasTotales', models.IntegerField()),
                ('archivo_pdf', models.FileField(blank=True, null=True, upload_to='pdfs-produccion')),
                ('prioridad', models.BooleanField(default=False)),
                ('fecha_finalizacion', models.DateTimeField()),
                ('creadoPor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ri_produccion.material')),
                ('placas', models.ManyToManyField(blank=True, to='ri_produccion.placa')),
                ('procesos', models.ManyToManyField(blank=True, to='ri_produccion.proceso')),
            ],
        ),
    ]
