# Generated by Django 4.2.5 on 2023-11-17 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ri_produccion', '0004_notificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='pieza',
            name='estatusAsignacion',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='HistorialPieza',
        ),
    ]
