# Generated by Django 4.2.5 on 2023-11-28 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ri_produccion', '0005_pieza_estatusasignacion_delete_historialpieza'),
    ]

    operations = [
        migrations.AddField(
            model_name='pieza',
            name='nombreProceso',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
