# Generated by Django 4.2.5 on 2023-11-29 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ri_produccion', '0006_pieza_nombreproceso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proceso',
            name='estatus',
            field=models.CharField(choices=[('error', 'Error'), ('rechazado', 'Rechañado'), ('pendiente', 'Pendiente'), ('operando', 'Operando'), ('realizado', 'Realizado')], default='pendiente', max_length=50),
        ),
    ]
