# Generated by Django 4.2.5 on 2023-11-14 21:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ri_produccion', '0006_proceso_prioridad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='necesitaNesteo',
        ),
        migrations.AddField(
            model_name='pieza',
            name='fechaCreado',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='placa',
            name='descripcion',
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
        migrations.AddField(
            model_name='placa',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='proceso',
            name='estatus',
            field=models.CharField(choices=[('error', 'Error'), ('rechazado', 'Rechazado'), ('pendiente', 'Pendiente'), ('operando', 'Operando'), ('realizado', 'Realizado')], default='pendiente', max_length=50),
        ),
    ]
