# Generated by Django 4.2.5 on 2023-11-14 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ri_produccion', '0007_remove_material_necesitanesteo_pieza_fechacreado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pieza',
            name='estatus',
            field=models.CharField(choices=[('rechazado', 'Rechazado'), ('pendiente', 'Pendiente'), ('aprobado', 'Aprobado')], default='pendiente', max_length=40),
        ),
    ]
