# Generated by Django 4.2.5 on 2023-12-05 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ri_produccion', '0007_alter_proceso_estatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='placa',
            name='requiere_nesteo',
            field=models.BooleanField(default=False),
        ),
    ]
