# Generated by Django 4.2.5 on 2023-12-05 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ri_produccion', '0008_placa_requiere_nesteo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placa',
            name='requiere_nesteo',
            field=models.BooleanField(default=True),
        ),
    ]
