# Generated by Django 4.2.5 on 2023-12-08 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ri_produccion', '0010_remove_placa_requiere_nesteo_pieza_requiere_nesteo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proceso',
            name='placa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ri_produccion.placa'),
        ),
    ]
