# Generated by Django 4.2.5 on 2023-12-08 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ri_produccion', '0011_alter_proceso_placa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placa',
            name='piezas',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
