runtime: python39
entrypoint: gunicorn -b :$PORT myapp.wsgi
instance_class: F2
automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 15
env_variables:
  DJANGO_SETTINGS_MODULE: "ri_project.settings"
