# Generated by Django 4.2.5 on 2023-09-12 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=15)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('rol', models.CharField(choices=[('MASTER', 'Master'), ('ADMINISTRADOR', 'Administrador'), ('SUPERVISOR', 'Supervisor'), ('COMPRADOR', 'Comprador'), ('CALIDAD', 'Calidad'), ('DISEÑADOR', 'Diseñador'), ('OPERADOR', 'Operador')], max_length=15)),
            ],
        ),
    ]
