# Generated by Django 4.2.5 on 2023-10-03 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ri_compras', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$NvSant6ltWlhUsJn5DHqz1$dut4U2LzuzYHDD678Vy7fYFHraSU/SqZvOQCNMc5ZbI=', max_length=128),
        ),
    ]
