# Generated by Django 4.2.5 on 2023-09-12 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ri_compras', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Material',
        ),
        migrations.AddField(
            model_name='usuarios',
            name='token',
            field=models.CharField(default='0', max_length=50),
        ),
    ]
