# Generated by Django 4.2.5 on 2023-10-27 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ri_compras', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$SBEPoR5b8YFCeIpQx2ot4s$Ze/GetL7dREDV/1GJrhBSWjNlx3/gqCSpC4QAPDpFCc=', max_length=128),
        ),
    ]
