# Generated by Django 4.2.5 on 2023-11-08 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ri_compras', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalusuarios',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$NzhiRPHkvzbA5rFvkq3VUS$SHh+gKoHYbq33qiZ+j6TS4DliZeVWG2GEuSYhmZx7iU=', max_length=128),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$NzhiRPHkvzbA5rFvkq3VUS$SHh+gKoHYbq33qiZ+j6TS4DliZeVWG2GEuSYhmZx7iU=', max_length=128),
        ),
    ]
