# Generated by Django 4.2.5 on 2023-10-10 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ri_compras', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalusuarios',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$IeIV0JAQas4gYygBPv6sg6$MM40AbNgR+efBI82V+lcLJgq9N3squix8q4rbQE9XAg=', max_length=128),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$IeIV0JAQas4gYygBPv6sg6$MM40AbNgR+efBI82V+lcLJgq9N3squix8q4rbQE9XAg=', max_length=128),
        ),
    ]
