# Generated by Django 4.2.5 on 2023-09-19 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ri_compras', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$MLPeEoaJWnXqQI1UqN8GPd$5vVCyZ3h1w4RTzwaDa+iPGAa2pch8bNc/mJTufqW+UQ=', max_length=128),
        ),
    ]
