# Generated by Django 4.2.5 on 2023-11-08 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ri_compras', '0002_alter_historicalusuarios_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalusuarios',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$YhHIVX1w0LgMPNrYMvqo5z$tcOkU4r26c2bRa1MIiH+V+/oGE8VPzfX9lHcTRxIIdM=', max_length=128),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$YhHIVX1w0LgMPNrYMvqo5z$tcOkU4r26c2bRa1MIiH+V+/oGE8VPzfX9lHcTRxIIdM=', max_length=128),
        ),
    ]
