# Generated by Django 4.2.5 on 2023-09-29 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ri_compras', '0002_alter_usuarios_password_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$2LrMlb6nwsnI6VvFTbCL1e$0NA35kuRmBnSqulimsLXdQLRR6CGz1fqUjRtt/Rxl4Q=', max_length=128),
        ),
    ]
