# Generated by Django 4.2.5 on 2023-10-03 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ri_compras', '0002_alter_usuarios_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicioRequisicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('divisa', models.CharField(default='MXN', max_length=5)),
            ],
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$EWACKt3iRtwf7pCenc2ENM$CBdgcSfI0ImXz66pj5hk5iD/Oq5sqLd9HsPYVdIzsCk=', max_length=128),
        ),
        migrations.AddField(
            model_name='requisicion',
            name='servicios',
            field=models.ManyToManyField(blank=True, to='ri_compras.serviciorequisicion'),
        ),
    ]
