# Generated by Django 4.2.5 on 2023-10-05 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ri_compras', '0002_alter_historicalusuarios_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproject',
            name='descripcion',
            field=models.TextField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='historicalproject',
            name='presupuesto',
            field=models.DecimalField(decimal_places=2, help_text='Dinero actual del proyecto.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='historicalusuarios',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$bDwCpldx6KTebR2dYQJx1s$6yPOy6pLi+Cya/jbF3zvhu4P9pJwAkZpLmxFG6ekDk0=', max_length=128),
        ),
        migrations.AlterField(
            model_name='project',
            name='descripcion',
            field=models.TextField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='project',
            name='presupuesto',
            field=models.DecimalField(decimal_places=2, help_text='Dinero actual del proyecto.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$bDwCpldx6KTebR2dYQJx1s$6yPOy6pLi+Cya/jbF3zvhu4P9pJwAkZpLmxFG6ekDk0=', max_length=128),
        ),
    ]
