# Generated by Django 4.2.5 on 2023-10-19 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ri_compras', '0003_alter_usuarios_password_historicalusuarios_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalusuarios',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$JdBAIKeWAG32dpd6F0u5Kk$7QA00clk+IjKMtDYXYKkziZokCjbcZaT+m2eJH6Kt6s=', max_length=128),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$JdBAIKeWAG32dpd6F0u5Kk$7QA00clk+IjKMtDYXYKkziZokCjbcZaT+m2eJH6Kt6s=', max_length=128),
        ),
    ]
