# Generated by Django 4.2.5 on 2023-09-29 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ri_compras', '0003_alter_usuarios_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$5mmdtYrnFvCdjKL5fOujy7$GCOzZP6+g9BqbewUF3Sb5qOB1jwIAKxppHLZplBBWng=', max_length=128),
        ),
    ]
