# Generated by Django 4.2.5 on 2023-10-06 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ri_compras', '0003_alter_historicalproject_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='contactos',
            field=models.ManyToManyField(to='ri_compras.contacto'),
        ),
        migrations.AlterField(
            model_name='historicalusuarios',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$4AoaCS3NRravEgWtlR8N7l$pv+ItYlGkUwKcukqMB3evd4/tpztDB4nGd+scczcmmE=', max_length=128),
        ),
        migrations.AlterField(
            model_name='historicalusuarios',
            name='telefono',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$4AoaCS3NRravEgWtlR8N7l$pv+ItYlGkUwKcukqMB3evd4/tpztDB4nGd+scczcmmE=', max_length=128),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='telefono',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
