# Generated by Django 4.2.5 on 2023-10-02 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ri_compras', '0003_alter_usuarios_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisicion',
            name='proyecto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requisiciones', to='ri_compras.project'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='tiempo_de_entegra_estimado',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$d4DAcFBjxVodSG2cZ3b4zY$TmkpA16KNQ1wU1DYCRunwS4UcOiWUlZND6ahhULoVog=', max_length=128),
        ),
    ]
