# Generated by Django 4.2.5 on 2023-09-12 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ri_compras', '0003_usuarios_is_active_usuarios_joined_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='token',
            field=models.CharField(max_length=50),
        ),
    ]
