# Generated by Django 4.2.5 on 2023-11-08 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ri_compras', '0003_alter_historicalusuarios_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='leido',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='historicalusuarios',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$keg5Tbjgq9d2UoHJjl0ra2$QTdgFljbLbKZ///LDoKvs+a3Meth2pc5894BvJNTjdc=', max_length=128),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$keg5Tbjgq9d2UoHJjl0ra2$QTdgFljbLbKZ///LDoKvs+a3Meth2pc5894BvJNTjdc=', max_length=128),
        ),
    ]
