# Generated by Django 4.2.5 on 2023-10-13 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ri_compras', '0003_alter_historicalusuarios_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalusuarios',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$lnbmbuzEmLMlTX6b495JwH$BWokdC78YThEqWjEkrSXm58vbgvSEABXIEAxql5QMVQ=', max_length=128),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$lnbmbuzEmLMlTX6b495JwH$BWokdC78YThEqWjEkrSXm58vbgvSEABXIEAxql5QMVQ=', max_length=128),
        ),
    ]
