# Generated by Django 4.2.5 on 2023-10-02 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ri_compras', '0004_requisicion_proyecto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$i1oVzY6F08Nbem6cVFJ1y3$wVXhwm6q0RoCTlW63JFwxFrclqzFqm8yhF6bGDwqZlk=', max_length=128),
        ),
    ]
