# Generated by Django 4.2.5 on 2023-10-13 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ri_compras', '0004_alter_historicalusuarios_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalusuarios',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$aZyUhSAZZXOKq7YVU9vF3G$z8HBU+rFhTqUjRtMagrOxQUGt6fLVghdeIaPrTQTlF0=', max_length=128),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$aZyUhSAZZXOKq7YVU9vF3G$z8HBU+rFhTqUjRtMagrOxQUGt6fLVghdeIaPrTQTlF0=', max_length=128),
        ),
    ]
