# Generated by Django 4.2.5 on 2023-10-19 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ri_compras', '0004_alter_historicalusuarios_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalordendecompra',
            name='url_pdf',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='ordendecompra',
            name='url_pdf',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='historicalusuarios',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$YHSTYi07MGQvnVNbZHx99c$c6nw08wIRrbApTjRoFau/nv3K9kO7pQE0CfF9W+Y8E0=', max_length=128),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$YHSTYi07MGQvnVNbZHx99c$c6nw08wIRrbApTjRoFau/nv3K9kO7pQE0CfF9W+Y8E0=', max_length=128),
        ),
    ]
