# Generated by Django 4.2.5 on 2023-10-04 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ri_compras', '0004_alter_usuarios_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='isr',
            field=models.DecimalField(decimal_places=2, max_digits=2, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='iva',
            field=models.DecimalField(decimal_places=2, max_digits=2, null=True),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$7nesDmG9BN0TypdqhDVNHY$asoOu48QtupIOXXmO7Lt73LgUXefMksaeBA5jQpTbro=', max_length=128),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='rol',
            field=models.CharField(choices=[('MASTER', 'Master'), ('ADMINISTRADOR', 'Administrador'), ('SUPERVISOR', 'Supervisor'), ('COMPRADOR', 'Comprador'), ('LIDER', 'Lider'), ('CALIDAD', 'Calidad'), ('DISEÑADOR', 'Diseñador'), ('OPERADOR', 'Operador'), ('PENDIENTE', 'Pendiente')], max_length=15, null=True),
        ),
    ]
