# Generated by Django 4.2.5 on 2023-11-08 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ri_compras', '0004_message_leido_alter_historicalusuarios_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalusuarios',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$aQ15bFhrzIFhAB3EsP9Mzr$BEO7TThKf30mKzZwnJFq5zP4vRegUR2sak6J0KU+4xQ=', max_length=128),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$aQ15bFhrzIFhAB3EsP9Mzr$BEO7TThKf30mKzZwnJFq5zP4vRegUR2sak6J0KU+4xQ=', max_length=128),
        ),
    ]
