# Generated by Django 4.2.5 on 2023-10-04 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ri_compras', '0005_proveedor_isr_proveedor_iva_alter_usuarios_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordendecompra',
            name='recibido',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ordendecompra',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$CzabrfuL7XGizIXopdOSri$yCA+Nyd8QpgamWa8CPGlR3HZhqOkcYGNrbQ69MKAd6o=', max_length=128),
        ),
    ]
