# Generated by Django 4.2.5 on 2023-10-02 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ri_compras', '0005_alter_usuarios_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisicion',
            name='total',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$360XnFiwto7wEkMBq89Vor$MBFoJpSmckluMWptmtuqgdViaUOTa9lXn6qO10yIEdA=', max_length=128),
        ),
    ]
