# Generated by Django 4.2.5 on 2023-09-13 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ri_compras', '0005_usuarios_groups_usuarios_is_superuser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$MoxXIybTA5VKarBSWlNwk4$8AatlxnzUtmyByFntvSHd0vPIBvwAOg+IlcSPDM3HPw=', max_length=128),
        ),
    ]
