# Generated by Django 4.2.5 on 2023-10-20 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ri_compras', '0005_historicalordendecompra_url_pdf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalordendecompra',
            name='url_pdf',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalusuarios',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$LJdNpycwO3fWJJaxEtV5sB$tqCGgi5CbBHolTle3aSxI9NfCjbJU4BZl96x/Be5cD8=', max_length=128),
        ),
        migrations.AlterField(
            model_name='ordendecompra',
            name='url_pdf',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$LJdNpycwO3fWJJaxEtV5sB$tqCGgi5CbBHolTle3aSxI9NfCjbJU4BZl96x/Be5cD8=', max_length=128),
        ),
    ]
