# Generated by Django 4.2.5 on 2023-10-13 20:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ri_compras', '0005_alter_historicalusuarios_password_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requisicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('motivo', models.TextField(blank=True)),
                ('total', models.IntegerField(default=0)),
                ('aprobado', models.CharField(choices=[('RECHAZADO', 'Rechazado'), ('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado')], default='PENDIENTE', max_length=50)),
                ('ordenado', models.BooleanField(default=False)),
                ('productos', models.ManyToManyField(blank=True, to='ri_compras.productorequisicion')),
                ('proveedor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requisiciones', to='ri_compras.proveedor')),
                ('proyecto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requisiciones', to='ri_compras.project')),
                ('servicios', models.ManyToManyField(blank=True, to='ri_compras.serviciorequisicion')),
            ],
        ),
        migrations.RenameModel(
            old_name='HistoricalRequisicionProyecto',
            new_name='HistoricalRequisicion',
        ),
        migrations.RemoveField(
            model_name='requisiciondepartamento',
            name='productos',
        ),
        migrations.RemoveField(
            model_name='requisiciondepartamento',
            name='proveedor',
        ),
        migrations.RemoveField(
            model_name='requisiciondepartamento',
            name='servicios',
        ),
        migrations.RemoveField(
            model_name='requisiciondepartamento',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='requisicionproyecto',
            name='productos',
        ),
        migrations.RemoveField(
            model_name='requisicionproyecto',
            name='proveedor',
        ),
        migrations.RemoveField(
            model_name='requisicionproyecto',
            name='proyecto',
        ),
        migrations.RemoveField(
            model_name='requisicionproyecto',
            name='servicios',
        ),
        migrations.RemoveField(
            model_name='requisicionproyecto',
            name='usuario',
        ),
        migrations.AlterModelOptions(
            name='historicalrequisicion',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical requisicion', 'verbose_name_plural': 'historical requisicions'},
        ),
        migrations.AlterField(
            model_name='historicalusuarios',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$nRxSrRkunGCZVQtmG40k8h$ydlEJPGTeOQ1snJ5iMeAASwOagVCduh5g+cqMwBJQv8=', max_length=128),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$nRxSrRkunGCZVQtmG40k8h$ydlEJPGTeOQ1snJ5iMeAASwOagVCduh5g+cqMwBJQv8=', max_length=128),
        ),
        migrations.DeleteModel(
            name='HistoricalRequisicionDepartamento',
        ),
        migrations.DeleteModel(
            name='RequisicionProyecto',
        ),
        migrations.AddField(
            model_name='requisicion',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requisiciones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicalordendecompra',
            name='requisicion',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ri_compras.requisicion'),
        ),
        migrations.AlterField(
            model_name='ordendecompra',
            name='requisicion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ri_compras.requisicion'),
        ),
        migrations.DeleteModel(
            name='RequisicionDepartamento',
        ),
    ]
