# Generated by Django 4.2.5 on 2023-10-06 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ri_compras', '0005_alter_historicalusuarios_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalusuarios',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$d0ouhEaPRZDKjqz2DoLebY$Iocnf2eKE5ivyYa+uwvZ90OCqbZyKgIq72l3JYZTJhw=', max_length=128),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$d0ouhEaPRZDKjqz2DoLebY$Iocnf2eKE5ivyYa+uwvZ90OCqbZyKgIq72l3JYZTJhw=', max_length=128),
        ),
    ]
