# Generated by Django 4.2.5 on 2023-10-30 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ri_compras', '0005_project_presupuesto_inicial_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproducto',
            name='costo',
            field=models.DecimalField(decimal_places=6, max_digits=30),
        ),
        migrations.AlterField(
            model_name='historicalusuarios',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$qLN0R7s1YurGeOxWULCeFb$rHklpyCHPY464vmTdetJb7i/Ta4asxkISJmmx5H/Irg=', max_length=128),
        ),
        migrations.AlterField(
            model_name='producto',
            name='costo',
            field=models.DecimalField(decimal_places=6, max_digits=30),
        ),
        migrations.AlterField(
            model_name='productorequisicion',
            name='costo',
            field=models.DecimalField(decimal_places=6, max_digits=30),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$qLN0R7s1YurGeOxWULCeFb$rHklpyCHPY464vmTdetJb7i/Ta4asxkISJmmx5H/Irg=', max_length=128),
        ),
    ]
