# Generated by Django 4.2.5 on 2023-11-09 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ri_compras', '0005_alter_historicalusuarios_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalusuarios',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$bRZRtR8sjCe6ZhjtKamzGY$uF1kww8VjxMOWcgHlwoyquLkI5M+bDRz4/CuDe0Rod0=', max_length=128),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$bRZRtR8sjCe6ZhjtKamzGY$uF1kww8VjxMOWcgHlwoyquLkI5M+bDRz4/CuDe0Rod0=', max_length=128),
        ),
    ]
