# Generated by Django 4.2.5 on 2023-09-29 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ri_compras', '0005_alter_usuarios_password_alter_usuarios_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='identificador',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='cantidad',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(default='Sin descripcion'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$pvUQL8dx2zs4v6GzdpC0SU$m3jryBEphyzGSmAW86iATHwxIcAogxLXLx93Yr1vYKw=', max_length=128),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='rol',
            field=models.CharField(choices=[('MASTER', 'Master'), ('ADMINISTRADOR', 'Administrador'), ('SUPERVISOR', 'Supervisor'), ('COMPRADOR', 'Comprador'), ('CALIDAD', 'Calidad'), ('DISEÑADOR', 'Diseñador'), ('OPERADOR', 'Operador'), ('PENDIENTE', 'Pendiente')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='telefono',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
