# Generated by Django 4.2.5 on 2023-10-04 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ri_compras', '0006_ordendecompra_recibido_alter_ordendecompra_total_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordendecompra',
            name='requisiciones',
        ),
        migrations.AddField(
            model_name='ordendecompra',
            name='requisicion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ri_compras.requisicion'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$2yC82fOCZtsnI4yb0xG8Ra$qVp0OY8+ZJANbjamVgxvg+tH8ySnQUeL7JJhRM4EV6E=', max_length=128),
        ),
    ]
