# Generated by Django 4.2.5 on 2023-10-06 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ri_compras', '0006_alter_historicalusuarios_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproveedor',
            name='correo',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproveedor',
            name='credito',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproveedor',
            name='dias_de_credito',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproveedor',
            name='direccion',
            field=models.CharField(help_text='Ej. Avenida Soles #8193', max_length=100),
        ),
        migrations.AlterField(
            model_name='historicalproveedor',
            name='direccion_geografica',
            field=models.CharField(help_text='Ej. Mexicali, B.C, Mexico', max_length=100),
        ),
        migrations.AlterField(
            model_name='historicalproveedor',
            name='pagina',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='historicalproveedor',
            name='razon_social',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='historicalproveedor',
            name='regimen_fiscal',
            field=models.CharField(choices=[('MASTER', 'Master')], max_length=50),
        ),
        migrations.AlterField(
            model_name='historicalproveedor',
            name='rfc',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='historicalproveedor',
            name='telefono',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproveedor',
            name='tiempo_de_entegra_estimado',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='historicalusuarios',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$CBAplaOwgF45F5UIZF62P8$/iQ7G3QIFkW6U2MjwcfYcFdoFnvJ6m1d2ODkZ2E3pIM=', max_length=128),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='correo',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='credito',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='dias_de_credito',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='direccion',
            field=models.CharField(help_text='Ej. Avenida Soles #8193', max_length=100),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='direccion_geografica',
            field=models.CharField(help_text='Ej. Mexicali, B.C, Mexico', max_length=100),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='pagina',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='razon_social',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='regimen_fiscal',
            field=models.CharField(choices=[('MASTER', 'Master')], max_length=50),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='rfc',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='telefono',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='tiempo_de_entegra_estimado',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$CBAplaOwgF45F5UIZF62P8$/iQ7G3QIFkW6U2MjwcfYcFdoFnvJ6m1d2ODkZ2E3pIM=', max_length=128),
        ),
    ]
