# Generated by Django 4.2.5 on 2023-10-20 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ri_compras', '0006_alter_historicalordendecompra_url_pdf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalrequisicion',
            name='fecha_aprobado',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='requisicion',
            name='fecha_aprobado',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='historicalusuarios',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$kGyfNluOxJbMsMKCzLAijT$OKOHn4ysenkgDBdnj+b2657mFe1Utp3t8rxKSywFIJQ=', max_length=128),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$kGyfNluOxJbMsMKCzLAijT$OKOHn4ysenkgDBdnj+b2657mFe1Utp3t8rxKSywFIJQ=', max_length=128),
        ),
    ]
