# Generated by Django 4.2.5 on 2023-10-02 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ri_compras', '0006_requisicion_total_alter_usuarios_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisicion',
            name='proveedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requisiciones', to='ri_compras.proveedor'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$jXAFpfegw66BpxY468XYzU$lMxmG2yzqo2R31gvA2MHmaEYaELQBgV1kDvyWjmwaxQ=', max_length=128),
        ),
    ]
