# Generated by Django 4.2.5 on 2023-10-13 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ri_compras', '0006_requisicion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalusuarios',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$aM8dy6aFVe7uXr7Ybxi0Fe$43ABXQ9m/R1Yue4+Pp7ap7YxPl1fj9gc3NK/RUCEAgE=', max_length=128),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$aM8dy6aFVe7uXr7Ybxi0Fe$43ABXQ9m/R1Yue4+Pp7ap7YxPl1fj9gc3NK/RUCEAgE=', max_length=128),
        ),
    ]
