# Generated by Django 4.2.5 on 2023-11-09 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ri_compras', '0006_alter_historicalusuarios_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalusuarios',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$971hE28NlLywDHoO44r06D$opo5UQUwa1Qyx8+WX/cbtukxDjCVcc/VFgRv5EUY7RU=', max_length=128),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$971hE28NlLywDHoO44r06D$opo5UQUwa1Qyx8+WX/cbtukxDjCVcc/VFgRv5EUY7RU=', max_length=128),
        ),
    ]
