# Generated by Django 4.2.5 on 2023-10-30 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ri_compras', '0006_alter_historicalproducto_costo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='ingreso_fijo',
            field=models.DecimalField(decimal_places=6, help_text='El ingreso que se mantendra mes con mes.', max_digits=30),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='presupuesto',
            field=models.DecimalField(decimal_places=6, help_text='Dinero actual en el departamento.', max_digits=30),
        ),
        migrations.AlterField(
            model_name='historicaldepartamento',
            name='ingreso_fijo',
            field=models.DecimalField(decimal_places=6, help_text='El ingreso que se mantendra mes con mes.', max_digits=30),
        ),
        migrations.AlterField(
            model_name='historicaldepartamento',
            name='presupuesto',
            field=models.DecimalField(decimal_places=6, help_text='Dinero actual en el departamento.', max_digits=30),
        ),
        migrations.AlterField(
            model_name='historicalusuarios',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$P8UDeVOpIXjZOfr6ILjg6p$SXvrt0Wb7T68TS8Xwbibbv1a3sVIzeoGkhH7TLidnAY=', max_length=128),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$P8UDeVOpIXjZOfr6ILjg6p$SXvrt0Wb7T68TS8Xwbibbv1a3sVIzeoGkhH7TLidnAY=', max_length=128),
        ),
    ]
