# Generated by Django 4.2.5 on 2023-09-13 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ri_compras', '0007_alter_usuarios_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$sf4rA6QdAtOYEYFER1LY8a$Eo9x3ak25+rSS5e2ShdI1dXDRIToOmvNGV84YrRsbQQ=', max_length=128),
        ),
    ]
