# Generated by Django 4.2.5 on 2023-10-30 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ri_compras', '0007_alter_departamento_ingreso_fijo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalordendecompra',
            name='total',
            field=models.DecimalField(decimal_places=6, max_digits=30),
        ),
        migrations.AlterField(
            model_name='historicalproveedor',
            name='credito',
            field=models.DecimalField(decimal_places=6, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproveedor',
            name='isr_retenido',
            field=models.DecimalField(decimal_places=6, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproveedor',
            name='iva',
            field=models.DecimalField(decimal_places=6, max_digits=20),
        ),
        migrations.AlterField(
            model_name='historicalproveedor',
            name='iva_retenido',
            field=models.DecimalField(decimal_places=6, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='historicalrequisicion',
            name='total',
            field=models.DecimalField(decimal_places=6, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='historicalusuarios',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$9w6ZRrjLHYFcrDvnJfcaug$4VRC2BSE/FXfdu345LYCJ+0pbfDpufE+98t5bD1zmwk=', max_length=128),
        ),
        migrations.AlterField(
            model_name='ordendecompra',
            name='total',
            field=models.DecimalField(decimal_places=6, max_digits=30),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='credito',
            field=models.DecimalField(decimal_places=6, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='isr_retenido',
            field=models.DecimalField(decimal_places=6, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='iva',
            field=models.DecimalField(decimal_places=6, max_digits=20),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='iva_retenido',
            field=models.DecimalField(decimal_places=6, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='requisicion',
            name='total',
            field=models.DecimalField(decimal_places=6, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$9w6ZRrjLHYFcrDvnJfcaug$4VRC2BSE/FXfdu345LYCJ+0pbfDpufE+98t5bD1zmwk=', max_length=128),
        ),
    ]
