# Generated by Django 4.2.5 on 2023-10-02 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ri_compras', '0007_requisicion_proveedor_alter_usuarios_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$pE9rtUdnWJpZh3dhDHmd63$wXo8UdpbySHIY3GsgkIIeze8mv+PfQL4PMYJkd9QtLs=', max_length=128),
        ),
    ]
