# Generated by Django 4.2.5 on 2023-10-13 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ri_compras', '0007_alter_historicalusuarios_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalusuarios',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$x3GOb9x7YAnFCLTTIMJgec$FmgI94SWBswfRXqRP8uuhaRzFz5FOcQt36d01QuP29U=', max_length=128),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$x3GOb9x7YAnFCLTTIMJgec$FmgI94SWBswfRXqRP8uuhaRzFz5FOcQt36d01QuP29U=', max_length=128),
        ),
    ]
