# Generated by Django 4.2.5 on 2023-10-04 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ri_compras', '0007_remove_ordendecompra_requisiciones_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisicion',
            name='ordenado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$ODhxZJ5NgOQHuM80sX61DV$nmUTJKn3zetyotWo8B+OuYbqMXTHHm5wBrMOQuuemBc=', max_length=128),
        ),
    ]
