# Generated by Django 4.2.5 on 2023-11-09 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ri_compras', '0008_alter_historicalusuarios_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalusuarios',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$PxrIZWjZfQZbcGnrPDaDcS$1d9JEOGSdZZ5ukr/q/SdCapIyCKP8/U8GROWwZO9Lrk=', max_length=128),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$PxrIZWjZfQZbcGnrPDaDcS$1d9JEOGSdZZ5ukr/q/SdCapIyCKP8/U8GROWwZO9Lrk=', max_length=128),
        ),
    ]
