# Generated by Django 4.2.5 on 2023-10-21 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ri_compras', '0008_remove_historicalordendecompra_recibido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalusuarios',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$PsLhFlughgyTaOpcxdsltO$8qxiE15YJKSHLjodCBiuOmzAMsfoCRy3Y4XhoKbQXto=', max_length=128),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$PsLhFlughgyTaOpcxdsltO$8qxiE15YJKSHLjodCBiuOmzAMsfoCRy3Y4XhoKbQXto=', max_length=128),
        ),
    ]
