# Generated by Django 4.2.5 on 2023-10-05 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ri_compras', '0008_requisicion_ordenado_alter_usuarios_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='isr',
            field=models.DecimalField(decimal_places=2, max_digits=2),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='iva',
            field=models.DecimalField(decimal_places=2, max_digits=2),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$ZcJePCDaVBc6ZZGSo4Rcca$8ykhmNENHxsZYFTgqtGeyyOjPf99tf01ZfkWHXrEjIk=', max_length=128),
        ),
    ]
