# Generated by Django 4.2.5 on 2023-09-13 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ri_compras', '0008_alter_usuarios_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$jBianbTBPq47kI51qhcRdp$VMQBuLgExtyB+vIz/MkoTHNDIOuPf+4mSdP37YBkL4A=', max_length=128),
        ),
    ]
