# Generated by Django 4.2.5 on 2023-10-30 18:31

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ri_compras', '0008_alter_historicalordendecompra_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproject',
            name='presupuesto',
            field=models.DecimalField(decimal_places=6, default=Decimal('0.0'), help_text='Dinero actual del proyecto.', max_digits=30),
        ),
        migrations.AlterField(
            model_name='historicalproject',
            name='presupuesto_inicial',
            field=models.DecimalField(decimal_places=6, help_text='Dinero inicial del proyecto.', max_digits=30),
        ),
        migrations.AlterField(
            model_name='historicalusuarios',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$uUK5rbsXB7BiSzLwerc0Vj$YxAxgbe+DTNRtnEk2ejNRIriK8Vtwe9x6zm2ao115+Y=', max_length=128),
        ),
        migrations.AlterField(
            model_name='project',
            name='presupuesto',
            field=models.DecimalField(decimal_places=6, default=Decimal('0.0'), help_text='Dinero actual del proyecto.', max_digits=30),
        ),
        migrations.AlterField(
            model_name='project',
            name='presupuesto_inicial',
            field=models.DecimalField(decimal_places=6, help_text='Dinero inicial del proyecto.', max_digits=30),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$uUK5rbsXB7BiSzLwerc0Vj$YxAxgbe+DTNRtnEk2ejNRIriK8Vtwe9x6zm2ao115+Y=', max_length=128),
        ),
    ]
