# Generated by Django 4.2.5 on 2023-10-30 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ri_compras', '0009_alter_historicalproject_presupuesto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalusuarios',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$3YGV4nn6ULTp5EcRJl5GWJ$b6G6D8Xv5rYSNT49KPp3ksQBtISsTTML+kpod8+3MLk=', max_length=128),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$3YGV4nn6ULTp5EcRJl5GWJ$b6G6D8Xv5rYSNT49KPp3ksQBtISsTTML+kpod8+3MLk=', max_length=128),
        ),
    ]
