# Generated by Django 4.2.5 on 2023-09-13 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ri_compras', '0009_alter_usuarios_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$LBCjEiffQOBrqfGBZnG24n$z66+ViPtcbTpqxv4ErT0tn/QyZ84k1z34gzYq6wWOEs=', max_length=128),
        ),
    ]
