# Generated by Django 4.2.5 on 2023-11-10 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ri_compras', '0009_alter_historicalusuarios_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalusuarios',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$SI3pz9WIVvUjFEdKW4Z7k7$RbShsy4JPoAEJoGiL1XGewxEW/V5LQ/Q8Sf/q6ee7A4=', max_length=128),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$SI3pz9WIVvUjFEdKW4Z7k7$RbShsy4JPoAEJoGiL1XGewxEW/V5LQ/Q8Sf/q6ee7A4=', max_length=128),
        ),
    ]
