# Generated by Django 4.2.5 on 2023-10-24 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ri_compras', '0009_alter_historicalusuarios_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproducto',
            name='unidad_de_medida',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='unidad_de_medida',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='productorequisicion',
            name='unidad_de_medida',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='historicalusuarios',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$ayHEAaaEmTdB8OQ8OU2Xyi$nFvUxOw556DVIpioScCjcSMonEnlDf7iEsRn6axhTH0=', max_length=128),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$ayHEAaaEmTdB8OQ8OU2Xyi$nFvUxOw556DVIpioScCjcSMonEnlDf7iEsRn6axhTH0=', max_length=128),
        ),
    ]
