# Generated by Django 4.2.5 on 2023-10-25 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ri_compras', '0010_historicalproducto_unidad_de_medida_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalrequisicion',
            name='fecha_ordenado',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='requisicion',
            name='fecha_ordenado',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='historicalusuarios',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$wI6bTglniBbyRCQlacZsLF$hxDGW7l8ezWzZyFFyRKoWWDa1PhwOF+KkwK4pCIDGMI=', max_length=128),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$wI6bTglniBbyRCQlacZsLF$hxDGW7l8ezWzZyFFyRKoWWDa1PhwOF+KkwK4pCIDGMI=', max_length=128),
        ),
    ]
