# Generated by Django 4.2.5 on 2023-09-13 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ri_compras', '0010_alter_usuarios_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$NFmgHTSBYmQOXKYr85bRWK$IkM8sLbwWzx6btHtGL1fTHeohWpyQ/BgleSHBZL9suQ=', max_length=128),
        ),
    ]
