# Generated by Django 4.2.5 on 2023-10-30 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ri_compras', '0010_alter_historicalusuarios_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalusuarios',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$GoJYI7dWlybJVRKSPFlEpk$LhRrHhUzr0NHrEYn2zdcPK1qR1TBma8zSdBQQ3+ZsGY=', max_length=128),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$GoJYI7dWlybJVRKSPFlEpk$LhRrHhUzr0NHrEYn2zdcPK1qR1TBma8zSdBQQ3+ZsGY=', max_length=128),
        ),
    ]
