# Generated by Django 4.2.5 on 2023-11-10 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ri_compras', '0010_alter_historicalusuarios_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalusuarios',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$xGA8Wx2eWalRtszuXPWp2Y$LTxq8mvgZurpl7fy9sIe/rz1evlQO5/CDG6ieoYrZaY=', max_length=128),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$xGA8Wx2eWalRtszuXPWp2Y$LTxq8mvgZurpl7fy9sIe/rz1evlQO5/CDG6ieoYrZaY=', max_length=128),
        ),
    ]
