# Generated by Django 4.2.5 on 2023-10-30 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ri_compras', '0011_alter_historicalusuarios_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalusuarios',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$HTsFZR58xNP9YttDHEQT5I$f912j2hfESMC26Wmko6asVXkc7/cz/7LTN/nFK63cyQ=', max_length=128),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$HTsFZR58xNP9YttDHEQT5I$f912j2hfESMC26Wmko6asVXkc7/cz/7LTN/nFK63cyQ=', max_length=128),
        ),
    ]
