# Generated by Django 4.2.5 on 2023-09-13 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ri_compras', '0011_alter_usuarios_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$LTwxp2uTWjftRKwyw7OF66$/HzzMQQ6HwVoVy2AGfL8CqLgxLFc+VIEpfCIb7lP/vo=', max_length=128),
        ),
    ]
