# Generated by Django 4.2.5 on 2023-10-25 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ri_compras', '0011_historicalrequisicion_fecha_ordenado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalusuarios',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$zFI8tb2uM7CZP5MYHlBbCL$BL9dIVkBBZq6NC87/2uVLW4+iNzSCf3bf8Vw3nTqKfE=', max_length=128),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$zFI8tb2uM7CZP5MYHlBbCL$BL9dIVkBBZq6NC87/2uVLW4+iNzSCf3bf8Vw3nTqKfE=', max_length=128),
        ),
    ]
