# Generated by Django 4.2.5 on 2023-09-13 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ri_compras', '0012_alter_usuarios_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$WubiXPC2Hur9wQnwvlXhwI$vnQ4MeT9Bh11yszY2NPCKwnq4ZD9OqICG4MJN1tbGWk=', max_length=128),
        ),
    ]
