# Generated by Django 4.2.5 on 2023-09-13 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ri_compras', '0013_alter_usuarios_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='token',
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$2Nua3PQuziBkzKVilmrIqa$LYNzvkcDp+aCthEvRxKPNo9NjU9l+atC1OvjJGIaHcw=', max_length=128),
        ),
    ]
