# Generated by Django 4.2.5 on 2023-10-30 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ri_compras', '0013_alter_historicalusuarios_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalusuarios',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$DuGVmxEE9fV56zvB5S1ez3$uIDvhmVv7lKBHsrOFG0F5ntXwBD6ev7WMk1vRp5/zuw=', max_length=128),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$DuGVmxEE9fV56zvB5S1ez3$uIDvhmVv7lKBHsrOFG0F5ntXwBD6ev7WMk1vRp5/zuw=', max_length=128),
        ),
    ]
