# Generated by Django 4.2.5 on 2023-11-11 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ri_compras', '0013_alter_historicalusuarios_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalusuarios',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$2A7STnxO8HMJJpLAwGxxxy$BhgC9/YmweQ53qLWVtmhAdpjH7DTolyhOuE5hq7Kjbk=', max_length=128),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$2A7STnxO8HMJJpLAwGxxxy$BhgC9/YmweQ53qLWVtmhAdpjH7DTolyhOuE5hq7Kjbk=', max_length=128),
        ),
    ]
