# Generated by Django 4.2.5 on 2023-10-25 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ri_compras', '0013_alter_historicalusuarios_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalusuarios',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$m8dKGUPLESBakybuwuWobE$iFS4JEuLcFev4sTXO7TenPMJLLVy09Q3yo414b8l/Qg=', max_length=128),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$m8dKGUPLESBakybuwuWobE$iFS4JEuLcFev4sTXO7TenPMJLLVy09Q3yo414b8l/Qg=', max_length=128),
        ),
    ]
