# Generated by Django 4.2.5 on 2023-10-25 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ri_compras', '0014_alter_historicalusuarios_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalusuarios',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$d64EGMxtq8Bgna0CuOoUN2$iSu97nVUl5fvvEhKiNxS1t1jrtjd2AC2nOPiFv1fIlA=', max_length=128),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$d64EGMxtq8Bgna0CuOoUN2$iSu97nVUl5fvvEhKiNxS1t1jrtjd2AC2nOPiFv1fIlA=', max_length=128),
        ),
    ]
