# Generated by Django 4.2.5 on 2023-10-31 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ri_compras', '0015_alter_historicalusuarios_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproducto',
            name='identificador',
            field=models.CharField(blank=True, help_text='Codigo o numero identificador', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalusuarios',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$uqncTXnm6hLW8hBwV6hPMd$cIRptuLPS7Z7fB6DMsEFnY449THzKUAHcXgtdLZ7ozI=', max_length=128),
        ),
        migrations.AlterField(
            model_name='producto',
            name='identificador',
            field=models.CharField(blank=True, help_text='Codigo o numero identificador', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='productorequisicion',
            name='identificador',
            field=models.CharField(blank=True, help_text='Codigo o numero identificador', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='productorequisicion',
            name='unidad_de_medida',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$uqncTXnm6hLW8hBwV6hPMd$cIRptuLPS7Z7fB6DMsEFnY449THzKUAHcXgtdLZ7ozI=', max_length=128),
        ),
    ]
