# Generated by Django 4.2.5 on 2023-10-25 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ri_compras', '0015_alter_historicalusuarios_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalusuarios',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$VrZPQTGPWzonD8xoU3ZSIV$pUtK/53MAqe3y0QoE0l4c4QKt0g9731FOtxklGcoDA8=', max_length=128),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$VrZPQTGPWzonD8xoU3ZSIV$pUtK/53MAqe3y0QoE0l4c4QKt0g9731FOtxklGcoDA8=', max_length=128),
        ),
    ]
