# Generated by Django 4.2.5 on 2023-09-13 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ri_compras', '0015_alter_usuarios_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$kGVl79ruMcsthgDVUxVGyb$XDnfRrRNaz4etmlSueqRYs6DjP1l6+y85/h+udvLDlo=', max_length=128),
        ),
    ]
