# Generated by Django 4.2.5 on 2023-09-13 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ri_compras', '0016_alter_usuarios_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$nfTCNO1xHcNRkBZ2OXX4UL$6y4rqbnFORInta3Z0n0ZCKx3eKaFg36yvcCFSxyhWk0=', max_length=128),
        ),
    ]
