# Generated by Django 4.2.5 on 2023-11-14 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ri_compras', '0016_alter_historicalusuarios_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalusuarios',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$1tWCnmkh9CBk9E2G9EQEZm$2L0c2lzf/MzkaCJVha+a2TevftRthOSjaeXTz60OlqA=', max_length=128),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$1tWCnmkh9CBk9E2G9EQEZm$2L0c2lzf/MzkaCJVha+a2TevftRthOSjaeXTz60OlqA=', max_length=128),
        ),
    ]
