# Generated by Django 4.2.5 on 2023-10-25 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ri_compras', '0016_alter_historicalusuarios_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalusuarios',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$jdnck3huXBC2c6Ijg1fm87$4iK30oR+S/Sf8kc9Vg+2akbov0G7rn+yUlinNa/7/T4=', max_length=128),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$jdnck3huXBC2c6Ijg1fm87$4iK30oR+S/Sf8kc9Vg+2akbov0G7rn+yUlinNa/7/T4=', max_length=128),
        ),
    ]
