# Generated by Django 4.2.5 on 2023-10-31 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ri_compras', '0016_alter_historicalproducto_identificador_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalrequisicion',
            name='tipo_de_cambio',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='requisicion',
            name='tipo_de_cambio',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='historicalusuarios',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$53EaiRuXQWYBM5LxWEELF9$JPwbS7Jnpjjr7Vi05am1xU3IlOelTrxF01tmLyQtoqo=', max_length=128),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$53EaiRuXQWYBM5LxWEELF9$JPwbS7Jnpjjr7Vi05am1xU3IlOelTrxF01tmLyQtoqo=', max_length=128),
        ),
    ]
