# Generated by Django 4.2.5 on 2023-11-14 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ri_compras', '0017_alter_historicalusuarios_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalusuarios',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$8cZ9F3CIYw5jnf1UVYsVxE$26KSbzJNnepuvYdpSVn+8z9m5o3TFKa53nzxrnxotVo=', max_length=128),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$8cZ9F3CIYw5jnf1UVYsVxE$26KSbzJNnepuvYdpSVn+8z9m5o3TFKa53nzxrnxotVo=', max_length=128),
        ),
    ]
