# Generated by Django 4.2.5 on 2023-10-31 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ri_compras', '0017_historicalrequisicion_tipo_de_cambio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalrequisicion',
            name='tipo_de_cambio',
            field=models.DecimalField(decimal_places=6, default=18, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historicalusuarios',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$SrTRAV7UchHXM67Yys4Kd5$Ug7zSV51oN6wg0HHsX4dST4vMX8qVKNT3oPDNihvh2c=', max_length=128),
        ),
        migrations.AlterField(
            model_name='requisicion',
            name='tipo_de_cambio',
            field=models.DecimalField(decimal_places=6, default=18, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$SrTRAV7UchHXM67Yys4Kd5$Ug7zSV51oN6wg0HHsX4dST4vMX8qVKNT3oPDNihvh2c=', max_length=128),
        ),
    ]
