# Generated by Django 4.2.5 on 2023-09-13 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ri_compras', '0017_alter_usuarios_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$a2NRwXfWTDJA7cCwARO1xf$Z9q3yWcari6oMMBxOddDyq76QDom+ydWJz5id7qsJCE=', max_length=128),
        ),
    ]
