# Generated by Django 4.2.5 on 2023-10-31 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ri_compras', '0018_alter_historicalrequisicion_tipo_de_cambio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalrequisicion',
            name='tipo_de_cambio',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='historicalusuarios',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$Zpsr6bO3W4WMMPTkVZn0Bq$j19x06axufwAwbbkiWXWxxOUW/U3erLw9WDzf4V8oVo=', max_length=128),
        ),
        migrations.AlterField(
            model_name='requisicion',
            name='tipo_de_cambio',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$Zpsr6bO3W4WMMPTkVZn0Bq$j19x06axufwAwbbkiWXWxxOUW/U3erLw9WDzf4V8oVo=', max_length=128),
        ),
    ]
