# Generated by Django 4.2.5 on 2023-10-25 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ri_compras', '0018_remove_historicaldepartamento_history_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$LQBryqmukb4mvGndGDVi4F$wmBqBDZFTaX6WaceNiiEAPv6ve5xaAGySdR6h8e0gJg=', max_length=128),
        ),
    ]
