# Generated by Django 4.2.5 on 2023-11-14 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ri_compras', '0018_alter_historicalusuarios_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalusuarios',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$q4Kp7wzXAjahtNKg4uOW8k$HhPQuuy1ojlbYWHw3i19fyr4SBj4Tcxq1XVsADtqLCg=', max_length=128),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$q4Kp7wzXAjahtNKg4uOW8k$HhPQuuy1ojlbYWHw3i19fyr4SBj4Tcxq1XVsADtqLCg=', max_length=128),
        ),
    ]
