# Generated by Django 4.2.5 on 2023-09-13 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ri_compras', '0018_alter_usuarios_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$KNg7KHGvhnmDplICgSINyH$sONjGIF/YGdAFtp4M9SbjGZQKPSkpoidgrluNzicNYg=', max_length=128),
        ),
    ]
