# Generated by Django 4.2.5 on 2023-11-14 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ri_compras', '0019_alter_historicalusuarios_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalusuarios',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$cVEllgMPivqotdOgWInwSQ$dU/3XOobebjr3/XbC+Hl8n6rfGQYBPP/2j/tPwiMV00=', max_length=128),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$cVEllgMPivqotdOgWInwSQ$dU/3XOobebjr3/XbC+Hl8n6rfGQYBPP/2j/tPwiMV00=', max_length=128),
        ),
    ]
