# Generated by Django 4.2.5 on 2023-10-25 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ri_compras', '0019_alter_usuarios_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$abHT664zkTGlOhxdoGF73r$tZ9OhyTaDU9xKts9ZjebSzJCXgBT4ZQsdIYlUT1GXqw=', max_length=128),
        ),
    ]
