# Generated by Django 4.2.5 on 2023-09-13 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ri_compras', '0019_alter_usuarios_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$ctw59C9dsNfWp7AAgzE1xt$6OeKW8Za2sV4WMs0Z80gnke2X2nXtMQZ/ODBlyLyY/w=', max_length=128),
        ),
    ]
