# Generated by Django 4.2.5 on 2023-10-31 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ri_compras', '0019_alter_historicalrequisicion_tipo_de_cambio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalusuarios',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$jamuN3gHVRTNXts91RyaWz$4XMrUSZR//0Z17oF3GRXZ5anCTCbIP9avmEOCPvPQZY=', max_length=128),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$jamuN3gHVRTNXts91RyaWz$4XMrUSZR//0Z17oF3GRXZ5anCTCbIP9avmEOCPvPQZY=', max_length=128),
        ),
    ]
