# Generated by Django 4.2.5 on 2023-10-26 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ri_compras', '0020_alter_usuarios_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$AjF3RdIRtKfj57X4ZZ10KP$eQ7CQPF0TRDou16a5XFpJpiq7n4bQkNV4AjcwaSZnKA=', max_length=128),
        ),
    ]
