# Generated by Django 4.2.5 on 2023-11-01 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ri_compras', '0020_alter_historicalusuarios_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalusuarios',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$sN3I4Eb8FUFUN8NmuDRP6l$ibWJZuwnFkLzeYbqLheO+R+DGceeoosJ+v+4zh/UO+g=', max_length=128),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$sN3I4Eb8FUFUN8NmuDRP6l$ibWJZuwnFkLzeYbqLheO+R+DGceeoosJ+v+4zh/UO+g=', max_length=128),
        ),
    ]
