# Generated by Django 4.2.5 on 2023-09-13 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ri_compras', '0020_usuarios_is_staff_alter_usuarios_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$f2VlLUIZ1g0q3JXSh8hFt8$xWtCDNYP5coH2HB4foTeEq1IWWQArPFUAWwvULyqMQw=', max_length=128),
        ),
    ]
