# Generated by Django 4.2.5 on 2023-10-26 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ri_compras', '0021_alter_usuarios_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$NOPJ3O7spItqKPqDDt6U4K$JMktxQOOFSEhAgxnXKaJcpvxNRucya/K3YLUeFUk3gk=', max_length=128),
        ),
    ]
