# Generated by Django 4.2.5 on 2023-11-01 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ri_compras', '0021_alter_historicalusuarios_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacto',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='historicalcontacto',
            name='direccion',
        ),
        migrations.AlterField(
            model_name='historicalusuarios',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$6SeRyqn4mX1jAnv6qOMMG7$9Gl+YH1HMgwYZ4VhxkT4YiUmi5/cXSiLLGKosl27Yx8=', max_length=128),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$6SeRyqn4mX1jAnv6qOMMG7$9Gl+YH1HMgwYZ4VhxkT4YiUmi5/cXSiLLGKosl27Yx8=', max_length=128),
        ),
    ]
