# Generated by Django 4.2.5 on 2023-09-13 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ri_compras', '0021_alter_usuarios_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$50WNA6H9bUQBGdzgcwSdB8$niu4i0wqDYzEJ+B9t8HeQ5qj6Wjl5B5l1Op1ZpdKPtk=', max_length=128),
        ),
    ]
