# Generated by Django 4.2.5 on 2023-09-13 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ri_compras', '0022_alter_usuarios_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$K4Vpx6vlPKCTPbg7UciaxV$w59xP4geVQcdILDL1zT/qVDwXqjohJme1Y9jmlUwqpk=', max_length=128),
        ),
    ]
