# Generated by Django 4.2.5 on 2023-11-02 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ri_compras', '0022_remove_contacto_direccion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='divisa',
            field=models.CharField(choices=[('MXN', 'MXN'), ('USD', 'USD')], default='MXN', max_length=5),
        ),
        migrations.AlterField(
            model_name='historicaldepartamento',
            name='divisa',
            field=models.CharField(choices=[('MXN', 'MXN'), ('USD', 'USD')], default='MXN', max_length=5),
        ),
        migrations.AlterField(
            model_name='historicalproducto',
            name='divisa',
            field=models.CharField(choices=[('MXN', 'MXN'), ('USD', 'USD')], default='MXN', max_length=5),
        ),
        migrations.AlterField(
            model_name='historicalproject',
            name='divisa',
            field=models.CharField(choices=[('MXN', 'MXN'), ('USD', 'USD')], default='MXN', max_length=5),
        ),
        migrations.AlterField(
            model_name='historicalproveedor',
            name='correo',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalservicio',
            name='costo',
            field=models.DecimalField(decimal_places=6, max_digits=30),
        ),
        migrations.AlterField(
            model_name='historicalservicio',
            name='divisa',
            field=models.CharField(choices=[('MXN', 'MXN'), ('USD', 'USD')], default='MXN', max_length=5),
        ),
        migrations.AlterField(
            model_name='historicalusuarios',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$eYSInYrjwO09uY9k557lrj$/zFk8i4u3dvEU7Y4upxmwecVVlJLoIlcK6/nwLZY1g8=', max_length=128),
        ),
        migrations.AlterField(
            model_name='producto',
            name='divisa',
            field=models.CharField(choices=[('MXN', 'MXN'), ('USD', 'USD')], default='MXN', max_length=5),
        ),
        migrations.AlterField(
            model_name='productorequisicion',
            name='divisa',
            field=models.CharField(choices=[('MXN', 'MXN'), ('USD', 'USD')], default='MXN', max_length=5),
        ),
        migrations.AlterField(
            model_name='project',
            name='divisa',
            field=models.CharField(choices=[('MXN', 'MXN'), ('USD', 'USD')], default='MXN', max_length=5),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='correo',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='costo',
            field=models.DecimalField(decimal_places=6, max_digits=30),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='divisa',
            field=models.CharField(choices=[('MXN', 'MXN'), ('USD', 'USD')], default='MXN', max_length=5),
        ),
        migrations.AlterField(
            model_name='serviciorequisicion',
            name='costo',
            field=models.DecimalField(decimal_places=6, max_digits=30),
        ),
        migrations.AlterField(
            model_name='serviciorequisicion',
            name='divisa',
            field=models.CharField(choices=[('MXN', 'MXN'), ('USD', 'USD')], default='MXN', max_length=5),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$eYSInYrjwO09uY9k557lrj$/zFk8i4u3dvEU7Y4upxmwecVVlJLoIlcK6/nwLZY1g8=', max_length=128),
        ),
    ]
