# Generated by Django 4.2.5 on 2023-11-02 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ri_compras', '0023_alter_departamento_divisa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='correo',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcontacto',
            name='correo',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalusuarios',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$ZhX0VCqhXlNK6GYkAkcp5O$7v/BPX+sNAFIQWGdkkjIlEsG++WJyrSFrl/2lNXjndE=', max_length=128),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$ZhX0VCqhXlNK6GYkAkcp5O$7v/BPX+sNAFIQWGdkkjIlEsG++WJyrSFrl/2lNXjndE=', max_length=128),
        ),
    ]
