# Generated by Django 4.2.5 on 2023-09-13 18:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ri_compras', '0023_alter_usuarios_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='departamento',
            field=models.CharField(choices=[('COMPRAS', 'Compras'), ('MANUFACTORA', 'Manufactora'), ('PROYECTOS', 'Proyectos'), ('RECURSOS HUMANOS', 'Recursos Humanos'), ('ALMACEN', 'Almacen'), ('FINANZAS', 'Finanzas'), ('DISEÑO', 'Diseño'), ('ELETRONICA', 'Electronica'), ('PROGRAMACION', 'Electronica y Programacion'), ('ENSAMBLE', 'Ensamble'), ('DIRECCION GENERAL', 'Direccion General'), ('ENTRANTE', 'Entrante')], default='Entrante', max_length=50),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$fIAqQ2DkrOSR3fkQcctiRg$qGVBIMcfFPr4mEmvuFO/LJs54LC+j/RHhTipYnLFi9Y=', max_length=128),
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('presupuesto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('usuarios', models.ManyToManyField(blank=True, related_name='departamentos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
