# Generated by Django 4.2.5 on 2023-09-13 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ri_compras', '0024_usuarios_departamento_alter_usuarios_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$ZPsynKJrbpnZMpQXkWb5uq$M1jL1z1F18HWqYNm0uXXs/NAlMiC866U/+D5gjgdRqc=', max_length=128),
        ),
    ]
