# Generated by Django 4.2.5 on 2023-11-07 17:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ri_compras', '0024_alter_contacto_correo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalusuarios',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$8H9YKqdTgd7CymvsfRloXW$LcowBKovHon4r/1OW+5KFk0EBZmrwOC/swRHEwVJTLM=', max_length=128),
        ),
        migrations.AlterField(
            model_name='message',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ordendecompra',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ordenes_de_compra', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='proyectos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='requisicion',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='requisiciones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='departamento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='usuarios', to='ri_compras.departamento'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$8H9YKqdTgd7CymvsfRloXW$LcowBKovHon4r/1OW+5KFk0EBZmrwOC/swRHEwVJTLM=', max_length=128),
        ),
    ]
