# Generated by Django 4.2.5 on 2023-09-13 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ri_compras', '0025_alter_usuarios_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$9f7vWW8VNSZQWYYDvVYseX$FauMgCii5VjmHBdWojwjCE9mLkWgNNoNs8f0KjpF5L4=', max_length=128),
        ),
    ]
