# Generated by Django 4.2.5 on 2023-09-13 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ri_compras', '0026_alter_usuarios_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$w9k1XZ6GxsqTQG3iBDPeEX$T+6Mdf0eCr1i8G/unHXd5qgGRHB6t8LKFJUIMv34mzw=', max_length=128),
        ),
    ]
