# Generated by Django 4.2.5 on 2023-09-13 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ri_compras', '0027_alter_usuarios_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$QwPOneR6kxDmy6JpZeQTqm$KyfWn68Rp55a6fwsGFzshWzY+552zd4sx62ZCob8oKQ=', max_length=128),
        ),
    ]
