# Generated by Django 4.2.5 on 2023-09-13 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ri_compras', '0028_alter_departamento_nombre_alter_usuarios_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$teuKA99jFECak1p0SMw6t3$CbuRemcpWUL/PaEao+KFpUTSjM80JUdaVHUp7jRuRkU=', max_length=128),
        ),
    ]
