# Generated by Django 4.2.5 on 2023-09-13 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ri_compras', '0029_alter_usuarios_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$1g3HyMkGsVzKx9Y7pilfoR$hHf2p65xuyFGhegIT8/E2eK3mQHwLnLiy/8gziPoa3w=', max_length=128),
        ),
    ]
