# Generated by Django 4.2.5 on 2023-09-13 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ri_compras', '0030_alter_usuarios_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$bn5GIFiiC71fWENIJgVvjg$zJdRG4tkchT56cpQ8cq1ssuVO2imNl9khtHjFkO9WTs=', max_length=128),
        ),
    ]
