# Generated by Django 4.2.5 on 2023-09-13 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ri_compras', '0031_alter_usuarios_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departamento',
            name='usuarios',
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='departamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='ri_compras.departamento'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$D9hJxg3ycjeRSBNdFVPuwV$qYvyoYFMm8RnAyQKWZlMl8rufDNmkNCP+/9mDDXQ0HM=', max_length=128),
        ),
    ]
