# Generated by Django 4.2.5 on 2023-09-13 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ri_compras', '0032_remove_departamento_usuarios_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$5qXv3JbXzB14qIO5jTuwGZ$QL5dl8imXZw+4xGsw2yvriJYdAYUUDyBKJGTybeEXVM=', max_length=128),
        ),
    ]
