# Generated by Django 4.2.5 on 2023-09-13 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ri_compras', '0033_alter_usuarios_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$6iHEN1Dw2lqsXJ9gTwtW4T$iAi4sOs2qFiuR6lXa/GfXIAvB4odmnP0Csjc/gqGlck=', max_length=128),
        ),
    ]
