# Generated by Django 4.2.5 on 2023-09-13 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ri_compras', '0036_alter_usuarios_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$j4Rxdgbddejy1gVlxkfnoI$UK+UPkfcFgfZFiexus+n3R5i8m5A4uBxIOGCRsKlsqw=', max_length=128),
        ),
    ]
