# Generated by Django 4.2.5 on 2023-09-13 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ri_compras', '0037_alter_usuarios_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$NU1FvlUV2c4flaXm6Z6whU$ROkIojFB1g/FqT9d9Bkx2dyxq3wndfyZiS4FGU0wqPU=', max_length=128),
        ),
    ]
