# Generated by Django 4.2.5 on 2023-09-13 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ri_compras', '0038_alter_usuarios_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='departamento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='ri_compras.departamento'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$QrZIGdR6f9WzC7lDuTzrEq$ds3ynTD/7NAtMY7rcBBsSv/fi8PEc7+ZN7l3sHkXcLY=', max_length=128),
        ),
    ]
