# Generated by Django 4.2.5 on 2023-09-13 21:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('ri_compras', '0040_producto_alter_usuarios_password_componente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=15)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('rol', models.CharField(choices=[('MASTER', 'Master'), ('ADMINISTRADOR', 'Administrador'), ('SUPERVISOR', 'Supervisor'), ('COMPRADOR', 'Comprador'), ('CALIDAD', 'Calidad'), ('DISEÑADOR', 'Diseñador'), ('OPERADOR', 'Operador')], max_length=15)),
                ('is_staff', models.BooleanField(default=False)),
                ('password', models.CharField(default='pbkdf2_sha256$600000$IjDtcrwLWcIHeAKr37GxBr$Md7MolCGqL1VMvaJgDMKNUq9pYGP+8Wer7EbM8/sti0=', max_length=128)),
                ('departamento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='ri_compras.departamento')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='ri_compras_usuarios_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='ri_compras_usuarios_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Usuarios',
        ),
    ]
