# Generated by Django 4.2.5 on 2023-09-13 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ri_compras', '0042_usuarios_delete_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$qkjsJdlXz17S5MvNMXuy1g$OHyhJB6mvbO7ULWYlsFZ6woXBPY6dkn5xzEi9i0y2ko=', max_length=128),
        ),
    ]
