# Generated by Django 4.2.5 on 2023-09-13 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ri_compras', '0043_alter_usuarios_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$0y8LjRnjTZsjsy6B5ZXuO4$y9sQtJITg6FJsFvRylai+frWG/RItmqTqV79CMtoiMc=', max_length=128),
        ),
        migrations.CreateModel(
            name='Requisicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('motivo', models.TextField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('aprobado', models.BooleanField(default=False)),
                ('componente', models.ManyToManyField(blank=True, to='ri_compras.componente')),
                ('material', models.ManyToManyField(blank=True, to='ri_compras.producto')),
                ('servicio', models.ManyToManyField(blank=True, to='ri_compras.servicio')),
            ],
        ),
        migrations.AddField(
            model_name='usuarios',
            name='requisiciones',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requisiciones', to='ri_compras.requisicion'),
        ),
    ]
