# Generated by Django 4.2.5 on 2023-09-13 22:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ri_compras', '0044_servicio_alter_usuarios_password_requisicion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='requisiciones',
        ),
        migrations.AddField(
            model_name='requisicion',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requisiciones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$GOZJZs43QmlhoBSBtdEO1j$WsvsVbT4Jnrv5cywqT8rKYPFY+xr04DxwsqYWKiHW+0=', max_length=128),
        ),
    ]
