# Generated by Django 4.2.5 on 2023-09-13 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ri_compras', '0045_remove_usuarios_requisiciones_requisicion_usuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$ObL7Eo4CDr4bRqvaCRQqzc$wzLX3ENAQziF0cq37lZNsUGbtLndoTCNfUjXON0Y92w=', max_length=128),
        ),
    ]
