# Generated by Django 4.2.5 on 2023-09-13 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ri_compras', '0046_alter_usuarios_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$lqPQoYSFK7lPmcyMokBCs9$2nuouOW5NtHBoAy5SQ23y47U1YARGtkx67Z8IEjymUw=', max_length=128),
        ),
    ]
