# Generated by Django 4.2.5 on 2023-09-13 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ri_compras', '0047_alter_usuarios_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requisicion',
            name='usuario',
        ),
        migrations.AddField(
            model_name='usuarios',
            name='requisiciones',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requisiciones', to='ri_compras.requisicion'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$CJgooKaeioSjwlWCtBdc8t$YYQPdDWgzGis7rkhx4S5XQYls66T3g5xONsPk6/mvPw=', max_length=128),
        ),
    ]
