# Generated by Django 4.2.5 on 2023-09-13 23:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ri_compras', '0048_remove_requisicion_usuario_usuarios_requisiciones_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='requisiciones',
        ),
        migrations.AddField(
            model_name='requisicion',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requisiciones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$no6cL7tZ3dQ5g8pm2UQl7K$wccZvkan2CeYwEH1qLIgbf6jrB3z++tQK5NYg4/CQO4=', max_length=128),
        ),
    ]
