# Generated by Django 4.2.5 on 2023-09-13 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ri_compras', '0049_remove_usuarios_requisiciones_requisicion_usuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisicion',
            name='motivo',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$2DIKoJTiPKU2oHGhazWFKs$tWBcZrvHjgOjWAb9hypx3MVACEQ32Rws0DdxQmuWfJA=', max_length=128),
        ),
    ]
