# Generated by Django 4.2.5 on 2023-09-13 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ri_compras', '0050_alter_requisicion_motivo_alter_usuarios_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(blank=True, max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=15)),
                ('correo', models.EmailField(blank=True, max_length=254)),
                ('pagina', models.URLField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$80nFsOm8dRefQVapThro2Y$+G9aKWHDX/7pfHYdtenPyEEznbVIfZlzJq7uO6VgK0g=', max_length=128),
        ),
        migrations.CreateModel(
            name='OrdenDeCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_emision', models.DateTimeField(auto_now_add=True)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ri_compras.proveedor')),
                ('requisiciones', models.ManyToManyField(to='ri_compras.requisicion')),
            ],
        ),
    ]
