# Generated by Django 4.2.5 on 2023-09-14 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ri_compras', '0051_proveedor_alter_usuarios_password_ordendecompra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$zD4LMhE8cRX2ttgTkEoVDY$DKvZW0bWzghAF+a7jiFWw6GUBQtm3kAhlwK5NtuUUhM=', max_length=128),
        ),
    ]
