# Generated by Django 4.2.5 on 2023-09-14 16:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ri_compras', '0053_alter_usuarios_password_recibo'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordendecompra',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ordenes_de_compra', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$0WQYQyDo1gqnw0ottzcRE2$21EQpUpTVhzRWwF6ORaAKdaCyvBMl5zlXp95IQnYj2g=', max_length=128),
        ),
    ]
